"""Generate the immutable Python contract constants from the silverc artifact."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ARTIFACT = ROOT / "contracts" / "artifacts" / "ride-escrow.json"
OUTPUT = ROOT / "backend" / "ride_escrow_artifact.py"


def main() -> None:
    data = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    contract = data["contracts"]["RideEscrow"]
    compiled = contract["compiled"]
    bytecode_hex = bytes(compiled["bytecode"]).hex()
    template_hash = bytes(compiled["template_hash"]).hex()
    state_span = compiled["state_span"]
    state_fields = tuple(
        (field["name"], field["type"]) for field in contract["runtime_state"]["fields"]
    )
    entries = {
        name: {
            "dispatch_tag": entry["dispatch_tag"],
            "params": tuple((param["name"], param["type"]) for param in entry["params"]),
        }
        for name, entry in contract["entries"].items()
    }
    rendered = f'''# Generated by scripts/generate_contract_module.py. Do not edit by hand.
COMPILER_VERSION = {data["compiler_version"]!r}
BYTECODE_HEX = {bytecode_hex!r}
TEMPLATE_HASH_HEX = {template_hash!r}
STATE_OFFSET = {state_span["offset"]}
STATE_LENGTH = {state_span["len"]}
STATE_FIELDS = {state_fields!r}
ENTRIES = {entries!r}
'''
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
